name: example_tech_support
use_case: tech_support
description: "Пример политики для поддержки"
fields:
  - field_pattern: "semantic:FIO"
    level: PSEUDONYMIZED_REVERSIBLE
    transformer: fio.FioTokenizationTransformer
  - field_pattern: "semantic:Passport"
    level: PSEUDONYMIZED_REVERSIBLE
    transformer: passport.PassportTokenizationTransformer
  - field_pattern: "semantic:INN"
    level: PSEUDONYMIZED_REVERSIBLE
    transformer: inn.InnTokenizationTransformer
  - field_pattern: "semantic:Phone"
    level: PSEUDONYMIZED_REVERSIBLE
    transformer: phone.PhoneTokenizationTransformer
  - field_pattern: "semantic:Email"
    level: PSEUDONYMIZED_REVERSIBLE
    transformer: email.EmailTokenizationTransformer
